unit _FormNouveauPlan;

interface

uses
  Windows, Messages, SysUtils, Classes, Graphics,
  Controls, Forms, Dialogs, StdCtrls, ExtCtrls, Buttons, cxGraphics,
  cxControls, cxLookAndFeels, cxLookAndFeelPainters, cxContainer, cxEdit,
  cxTextEdit, cxMaskEdit, cxSpinEdit;
type
  TFormNouveauPlan=class(TForm)
    Panel1: TPanel;
    Panel2: TPanel;
    Bevel1: TBevel;
    Bevel2: TBevel;
    Image1: TImage;
    Label1: TLabel;
    EditTitre: TEdit;
    Label2: TLabel;
    Label3: TLabel;
    Label4: TLabel;
    EditAnneeScolaire: TEdit;
    Label5: TLabel;
    EditRemarque: TEdit;
    Label7: TLabel;
    ComboBoxUtilisateurs: TComboBox;
    SpeedButton2: TSpeedButton;
    SpeedButton3: TSpeedButton;
    SpeedButton4: TSpeedButton;
    ComboBox1: TComboBox;
    Label9: TLabel;
    ComboBox2: TComboBox;
    SpeedButton6: TSpeedButton;
    SpeedButton7: TSpeedButton;
    cxSpinEdit1: TcxSpinEdit;
    cxSpinEdit2: TcxSpinEdit;
    procedure SpeedButton3Click(Sender: TObject);
    procedure SpeedButton4Click(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end ;


{This file is generated by DeDe Ver 3.50.02 Copyright (c) 1999-2002 DaFixer}

implementation

{$R *.DFM}


{ TFormNouveauPlan }


{ TFormNouvelleClasse }

procedure TFormNouveauPlan.SpeedButton3Click(Sender: TObject);
begin
 ModalResult:=mrOk;
end;

procedure TFormNouveauPlan.SpeedButton4Click(Sender: TObject);
begin
 ModalResult:=mrCancel;
end;

end.
